version: '3'
services:
  app:
    build: .
    ports:
      - 8081:80
  web:
    image: node:14
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    volumes:
      - .:/app
    ports:
      - 8081:8080