version: '3.4'
services:
  web:
    build: .
    ports:
      - 8111:8080
  node:
    image: node:14
    working_dir: /app
    command: npm start
    ports:
      - 3111:3000
    volumes:
      - .:/app
