version: "3.7"

services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    volumes:
      - ./usr/app:/app
      - /app/node_modules
    expose:
      - "80"
    ports:
      - "8081:8081"
